### ISSUE TITLE
Add TestCaseName in Test definition and in test results 

### ISSUE THREAD

**Issue by brijrajsingh** [microsoft/webvalidate#15]
## Problem Statement

- At present if one is to run multiple tests, the only way to easily relate on which tests ran successfully and which failed is to relate using the sequence and the urls/methods for tests. Which makes it a little less intuitive. 

## Proposed Solution

- Adding testcasename in the test definition and return the same along with the test results.

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by bartr** [comment]
This is being tracked here:  https://github.com/retaildevcrews/webvalidate/issues/29
