### ISSUE TITLE
Publish webvalidate container image to official microsoft registry mcr.microsoft.com 

### ISSUE THREAD

**Issue by maniSbindra** [microsoft/webvalidate#17]
## Problem Statement
- The current documentation at https://github.com/microsoft/webvalidate, to execute WebV from a docker container sources the images from docker hub **retaildevcrew/webvalidate**
```docker run -it --rm retaildevcrew/webvalidate --server https://www.microsoft.com --files msft.json```

## Proposed Solution
-It will be good if the **WebV** docker image is available from **mcr.microsoft.com** , which as per https://github.com/microsoft/containerregistry is " the primary Registry for all Microsoft Published docker images that offers a reliable and trustworthy delivery of container images "

## Alternative Proposals
-The images can be pushed and made available from the Microsoft account on docker hub

## Additional Context

-

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by bartr** [comment]
This is not an "official" Microsoft supported product. It is a public repo with limited support. In order to make it "official", we would have to find a team willing to take on that responsibility which is beyond the limited support we can currently offer.

v2.0 is moving to ghcr.io/retaildevcrews
