### ISSUE TITLE
Add message to log when webvalidate stops execution due to default configuration of config.MaxErrors (10) being reached

### ISSUE THREAD

**Issue by maniSbindra** [microsoft/webvalidate#19]
## Problem Statement

- When 100s of tests are executed due to the default value of config.MaxErrors (which seems to be 10) the tests stop execution after 10 failures. At this point there is no message in the log that webvalidate stopped execution due to the error threshold being breached

## Proposed Solution

- Add a message to the log indicating that value of MaxErrors has been reached and hence further tests are not being executed

## Additional Context

- Without this one cannot understand looking at pipeline logs what went wrong

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by bartr** [comment]
Planned for v2.0 release

Tracked here:  https://github.com/retaildevcrews/webvalidate/issues/28
