### ISSUE TITLE
Provide option to publish webv report in Junit/xunit/nunit format which can be consumed in tools like Azure Pipelines

### ISSUE THREAD

**Issue by maniSbindra** [microsoft/webvalidate#20]
## Problem Statement

- Provide option to publish webv report in Junit/xunit/nunit format which can be consumed in tools like Azure Pipelines

## Proposed Solution
- Provide option to publish webv reports in one of the standard formats (Junit etc). This will allow the reports to be easily consumed in tools like Azure Pipelines
- Currently we use a custom script to publish webv report in Junit format, which appears as follows in the Azure Pipelines Dashboard 
![Slide1-main](https://user-images.githubusercontent.com/6338721/121301260-89e64d80-c915-11eb-89a4-162d3d485ae9.jpg)
![Slide2-main](https://user-images.githubusercontent.com/6338721/121301266-8ce13e00-c915-11eb-9007-d7eeaf62d168.jpg)

## Next Steps

- [ ] Team consensus to proceed
- [ ] Complete Design Review Template (if applicable)
- [ ] Schedule Design Session

**Comment by bartr** [comment]
included in WebV 2.1.0
